DATASET:
  BATCH_SIZE: 32
  WORKERS: 2
  MIN_FREQ: 1
  VOCAB:
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    USE_MAPPING: False
    PRETRAINED_LANGUAGE_MODEL: null
  JSON_PATH:
    TRAIN: features/OpenViVQA/annotations/OpenViVQA_train.json
    DEV: features/OpenViVQA/annotations/OpenViVQA_dev.json
    TEST: features/OpenViVQA/annotations/OpenViVQA_test.json
  FEATURE_PATH:
    FEATURES: features/OpenViVQA/features/x152++_faster_rcnn
    SCENE_TEXT: null
    IMAGE: null

TRAINING:
  CHECKPOINT_PATH: saved_models
  START_FROM: null
  LEARNING_RATE: 1.
  WARMUP: 10000
  GET_SCORES: False
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3

MODEL:
  ARCHITECTURE: EncoderDecoderTransformer
  NAME: extended_mcan_region_x152++
  DEVICE: cuda
  VISION_EMBEDDING:
    D_FEATURE: 1024
    D_MODEL: 512
    DROPOUT: 0.1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    D_MODEL: 512
    D_EMBEDDING: 300
    DROPOUT: 0.1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
  ENCODER:
    ARCHITECTURE: GuidedAttentionEncoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaleDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    GUIDED_ATTENTION:
      ARCHITECTURE: ScaleDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      ARCHITECTURE: ScaleDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: True
      DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1
